// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    AxiosDemo: typeof import('./src/components/Demo/AxiosDemo.vue')['default']
    Basic: typeof import('./src/components/Demo/Basic.vue')['default']
    Child: typeof import('./src/components/Demo/Child.vue')['default']
    Cont: typeof import('./src/components/Demo/Cont.vue')['default']
    Demo2: typeof import('./src/components/Demo/Demo2.vue')['default']
    Demo3: typeof import('./src/components/Demo/Demo3.vue')['default']
    Demo4: typeof import('./src/components/Demo/Demo4.vue')['default']
    Demo5: typeof import('./src/components/Demo/Demo5.vue')['default']
    Demo6: typeof import('./src/components/Demo/Demo6.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElContainer: typeof import('element-plus/es')['ElContainer']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElementUI: typeof import('./src/components/Demo/ElementUI.vue')['default']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElHeader: typeof import('element-plus/es')['ElHeader']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElMain: typeof import('element-plus/es')['ElMain']
    Father: typeof import('./src/components/Demo/Father.vue')['default']
    Footer: typeof import('./src/components/Head/Footer.vue')['default']
    Forget: typeof import('./src/components/Login/Forget.vue')['default']
    Head: typeof import('./src/components/Head/Head.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    LoginBox: typeof import('./src/components/Login/LoginBox.vue')['default']
    Name: typeof import('./src/components/Name.vue')['default']
    RegBox: typeof import('./src/components/Login/RegBox.vue')['default']
  }
}

export { }
