// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    Editor: typeof import('./src/components/Main/Editor.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCol: typeof import('element-plus/es')['ElCol']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElImage: typeof import('element-plus/es')['ElImage']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElRow: typeof import('element-plus/es')['ElRow']
    Forget: typeof import('./src/components/Login/Forget.vue')['default']
    Head: typeof import('./src/components/Head/Head.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    Item: typeof import('./src/components/Main/Item.vue')['default']
    ItemLabel: typeof import('./src/components/Main/ItemLabel.vue')['default']
    List: typeof import('./src/components/Main/List.vue')['default']
    LoginBox: typeof import('./src/components/Login/LoginBox.vue')['default']
    Main: typeof import('./src/components/Main/Main.vue')['default']
    Name: typeof import('./src/components/Name.vue')['default']
    RegBox: typeof import('./src/components/Login/RegBox.vue')['default']
  }
}

export { }
