// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    AxiosDemo: typeof import('./src/components/Demo/AxiosDemo.vue')['default']
    Basic: typeof import('./src/components/Demo/Basic.vue')['default']
    Child: typeof import('./src/components/Demo/Child.vue')['default']
    Cont: typeof import('./src/components/Demo/Cont.vue')['default']
    Demo2: typeof import('./src/components/Demo/Demo2.vue')['default']
    Demo3: typeof import('./src/components/Demo/Demo3.vue')['default']
    Demo4: typeof import('./src/components/Demo/Demo4.vue')['default']
    Demo5: typeof import('./src/components/Demo/Demo5.vue')['default']
    Demo6: typeof import('./src/components/Demo/Demo6.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElementUI: typeof import('./src/components/Demo/ElementUI.vue')['default']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElInput: typeof import('element-plus/es')['ElInput']
    Father: typeof import('./src/components/Demo/Father.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    Name: typeof import('./src/components/Name.vue')['default']
    RefUsePlan: typeof import('./src/components/Demo/RefUsePlan.vue')['default']
  }
}

export { }
